name: Terraform Sonarckoud Workflow
on:
  push:
    branches: 
      - master
  pull_request:
    types: [opened, synchronize, reopened]  

jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    name: Terraform Plan
    steps:
      - name: Install Terraform CLI
        uses: autero1/action-terraform@v0.1.0
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          terraform_version: 0.14.5
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Terraform Plan
        id: plan
        env:
          access_token: ${{secrets.SONAR_TOKEN}}
          host: ${{secrets.HOST}} 
        run: |
          echo "==> running terraform plan, please wait..."
          terraform init && terraform plan -out=plan.out && terraform show -json plan.out > plan.out.json
  TerraformApply:
      runs-on: ubuntu-latest
      needs: TerraformPlan
      name: Terraform Apply
      environment: production
      steps:  
      - name: Install Terraform CLI
        uses: autero1/action-terraform@v0.1.0
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          terraform_version: 0.13.5
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Terraform Apply
        env:
          access_token: ${{secrets.SONAR_TOKEN}}
          host: ${{secrets.HOST}} 
        run: |
          terraform init && terraform apply -auto-approve
