name: Terraform Sonarckoud Workflow
on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]  

jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    name: Terraform Plan
    steps:
      - name: Install Terraform CLI
        uses: autero1/action-terraform@v0.1.0
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          terraform_version: 0.14.5
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          TF_VAR_HOST: ${{ secrets.HOST }} 
        run: |
          echo "==> running terraform plan, please wait..."
          terraform init && terraform plan -out=plan.out && terraform show -json plan.out > plan.out.json
  TerraformApply:
      runs-on: ubuntu-latest
      needs: TerraformPlan
      name: Terraform Apply
      environment: production
      steps:  
      - name: Install Terraform CLI
        uses: autero1/action-terraform@v0.1.0
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          terraform_version: 0.13.5
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Enable Terraform Enterprise Authentication
        run: |
          mkdir -p ~/.terraform.d
          echo 'credentials "app.terraform.io" {' > ~/.terraform.d/credentials.tfrc.json
          echo '   token = "${{ secrets.TFE_TOKEN }}"'>> ~/.terraform.d/credentials.tfrc.json
          echo '}' >> ~/.terraform.d/credentials.tfrc.json
      - name: Terraform Apply
        env:
          TF_VAR_SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          TF_VAR_HOST: ${{ secrets.HOST }} 
        run: |
          terraform init && terraform apply -auto-approve
